name: Проверка скрипта на работоспособность
on: [push]
jobs:
  tests:
    name: Тесты скрипта
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Тест работоспособности кода
      run: |
        chmod +x script.sh
        ./script.sh
